#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═
#	Simple script to hide/show polybar
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

function hide() {
	
case "${RICETHEME}" in
    vanessa|silvia|pamela)
        polybar-msg cmd hide | bspc config top_padding 5
        ;;
    isabel)
        polybar-msg cmd hide | bspc config bottom_padding 5
        ;;
    z0mbi3)
        eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar close bar | bspc config left_padding 5
        ;;
		nelly)
        eww -c "$HOME"/.config/bspwm/rices/nelly/bar close bar | bspc config left_padding 5
        ;;
    *)
        echo "Error: Something fails dud.."
        ;;
esac
	
}

function unhide() {
	
case "${RICETHEME}" in
	vanessa|pamela)
		polybar-msg cmd show | bspc config top_padding 60
		;;
	silvia)
		polybar-msg cmd show | bspc config top_padding 50
		;;
	isabel)
		polybar-msg cmd show | bspc config bottom_padding 45
		;;
	z0mbi3)
		eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar open bar | bspc config left_padding 80
		;;
	nelly)
		eww -c "$HOME"/.config/bspwm/rices/nelly/bar open bar | bspc config left_padding 80
		;;
	*)
		echo "Error: Something fails dud.."
		;;
esac

}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac

