#!/usr/bin/env bash

power() {
    LOCKFILE_POWER="$HOME/.cache/eww-fer-power.lock"

if [[ ! -f "$LOCKFILE_POWER" ]]; then
    touch "$LOCKFILE_POWER"
    eww open powermenu -c ~/.config/bspwm/rices/fernanda/widgets/
elif [[ -f "$LOCKFILE_POWER" ]]; then
    eww close powermenu -c ~/.config/bspwm/rices/fernanda/widgets/
    rm "$LOCKFILE_POWER"
fi
}

profile() {
    LOCKFILE_PROFILE="$HOME/.cache/eww-fer-profile.lock"

if [[ ! -f "$LOCKFILE_PROFILE" ]]; then
    touch "$LOCKFILE_PROFILE"
    eww open launchermenu -c ~/.config/bspwm/rices/fernanda/widgets/
elif [[ -f "$LOCKFILE_PROFILE" ]]; then
    eww close launchermenu -c ~/.config/bspwm/rices/fernanda/widgets/
    rm "$LOCKFILE_PROFILE"
fi
}

mplayer() {
LOCKFILE_MPLAYER="$HOME/.cache/eww-fer-mplayer.lock"

if [[ ! -f "$LOCKFILE_MPLAYER" ]]; then
    touch "$LOCKFILE_MPLAYER"
    eww open music -c ~/.config/bspwm/rices/fernanda/widgets/
elif [[ -f "$LOCKFILE_MPLAYER" ]]; then
    eww close music -c ~/.config/bspwm/rices/fernanda/widgets/
    rm "$LOCKFILE_MPLAYER"
fi
}

calendar() {
    LOCKFILE_CALENDAR="$HOME/.cache/eww-fer-calendar.lock"

if [[ ! -f "$LOCKFILE_CALENDAR" ]]; then
    touch "$LOCKFILE_CALENDAR"
    eww open calendar -c ~/.config/bspwm/rices/fernanda/widgets/
elif [[ -f "$LOCKFILE_CALENDAR" ]]; then
    eww close calendar -c ~/.config/bspwm/rices/fernanda/widgets/
    rm "$LOCKFILE_CALENDAR"
fi
}

net_stat () {
    local ID="$(ip link | awk '/state UP/ {print $2}')"
    if command -v iwgetid >/dev/null 2>&1 ; then
        local SSID="$(iwgetid -r)"
    fi

    if (ping -c 1 archlinux.org || ping -c 1 google.com) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "Conectado"
            echo "fernanda.amber"
        else
            echo "$SSID"
            echo "fernanda.amber"
        fi
    else
        echo "Sin conexión"	
        echo "fernanda.red"
    fi
}

case "$1" in
	--powermenu)
		power;;
	--cardprofile)
		profile;;
	--musicplayer)
		mplayer;;
	--calendar)
		calendar;;
    --network)
        case "$2" in
            stat)
                net_stat | head -n1;;
            icon)
                net_stat | tail -n1;;
        esac;;
	*)
		echo "Error..";;
esac
