## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="""$directory$git_branch$character"""
right_format = """$git_status$cmd_duration"""
add_newline = true 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = false
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[❯](#90ceaa bold)"
error_symbol = "[❯](#dd6777)"
vicmd_symbol = "[](#ecd3a0)"

[directory]
format = "[ ]($style)[ ](bg:#86AAEC fg:#0d0f18)[$path](bg:#86AAEC fg:#0d0f10 bold)[ ]($style)"
style = "bg:none fg:#86AAEC"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#c296eb fg:#0d0f18 bold)$branch](bg:#c296eb fg:#0d0f18)[ ]($style)"
style = "bg:none fg:#c296eb"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#93cee9 fg:#0d0f18)[ ]($style)"
style = "bg:none fg:#93cee9"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count} ⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = " "
modified = "!${count}"
staged = "+${count}"
renamed = "» ${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#dd6777 fg:#0d0f18 bold)$duration](bg:#dd6777 fg:#0d0f18)[ ]($style)"
disabled = false
style = "bg:none fg:#dd6777"

