#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

xsetroot -cursor_name left_ptr &

bspc config border_width         1
bspc config focused_border_color \#5a1582
bspc config normal_border_color  \#543c5c
bspc config window_gap            5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc rule -a 'Brave-browser' desktop="^1" follow=on
bspc rule -a 'Google-chrome' desktop='^1' follow=on
bspc rule -a 'firefox' desktop='^1' follow=on
bspc rule -a 'Thunar' desktop="^4" state=floating follow=on
bspc rule -a 'org.gnome.Nautilus' state=floating follow=on
bspc rule -a 'gnome-calculator' state=floating follow=on
bspc rule -a 'Nitrogen' state=floating follow=on

# Auto start
picom &
nitrogen --restore & 
dunst &
$HOME/.config/polybar/launch.sh &
