#!/usr/bin/env bash
rofi_command="rofi -theme $HOME/.config/bspwm/rices/nelly/rofi/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
if [[ "$DIR" == "powermenus" ]]; then
	shutdown=""
	reboot=""
	lock=""
	logout=""
	ddir="$HOME/.config/bspwm/rices/nelly/rofi"
else

# For some reason the Icons are mess up I don't know why but to fix it uncomment section 2 and comment section 1 but if the section 1 icons are mess up uncomment section 2 and comment section 1

	# Buttons
	layout=`cat $HOME/.config/bspwm/rices/nelly/rofi/powermenu.rasi | grep BUTTON | cut -d'=' -f2 | tr -d '[:blank:],*/'`
	if [[ "$layout" == "TRUE" ]]; then
        shutdown=""
	    reboot=""
	    lock=""
	    logout=""
	else
		shutdown=" Apagar"
		reboot=" Reiniciar"
		lock=" Bloquear"
		logout=" Salir"
	fi
	ddir="$HOME/.config/bspwm/rices/nelly/rofi"
fi

# Confirm layout
cnflayout=`cat $ddir/confirm.rasi | grep USE_ICON | cut -d'=' -f2 | tr -d '[:blank:],*/'`
if [[ "$cnflayout" == "NO" ]]; then
    yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Confirmation CMD
confirm_cmd () {
    rofi -dmenu\
        -p "Confirmación "\
        -mesg "¿Estas seguro?" \
        -theme "$ddir/confirm.rasi"
}

# Ask for confirmation
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

confirm_run() {
    selected="$(confirm_exit)"
    if [[ "$selected" == "$yes" ]]; then
        ${1} && ${2} && ${3}
    else
        exit
    fi
}

# Variable passed to rofi
options="$lock\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
		confirm_run "shutdown now"
        ;;
    $reboot)
		confirm_run "reboot"
        ;;
    $lock)
        OpenApps --locker
        ;;
    $logout)
        confirm_run "killall bspwm"
        ;;
esac
