#!/usr/bin/env bash

ID="$(ip link | awk '/state UP/ {print $2}')"
if command -v iwgetid >/dev/null 2>&1 ; then
SSID="$(iwgetid -r)"
fi

net_stat () {
if (ping -c 1 archlinux.org || ping -c 1 google.com) &>/dev/null; then
	if [[ $ID == e* ]]; then
		echo "Conectado"
		echo "images/icons/system/wifi.svg"
	else
		echo "$SSID"
		echo "images/icons/system/wifi.svg"
	fi
else
	echo "Sin conexión"
	echo "images/icons/system/no-wifi.svg"	
fi
}

case "$1" in
	--stat)
		net_stat | head -n1;;
	--icon)
		net_stat | tail -n1;;
esac
