# Window configuration
[window]
opacity = 0.92

[window.dimensions]
columns = 71
lines = 19

# Font configuration
[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

# Colors (Tomorrow Night)
[colors]
[colors.primary]
background = "#0d0f18"
#background = "#1e1d2f"
foreground = "#a5b6cf"

[colors.normal]
black = "#3d414f"
red = "#dd6777"
green = "#90ceaa"
yellow = "#ecd3a0"
blue = "#86aaec"
magenta = "#c296eb"
cyan = "#93cee9"
white = "#cbced3"

[colors.bright]
black = "#3d414f"
red = "#dd6777"
green = "#90ceaa"
yellow = "#ecd3a0"
blue = "#86aaec"
magenta = "#c296eb"
cyan = "#93cee9"
white = "#cbced3"

[colors.cursor]
cursor = "#a5b6cf"
text = "#0d0f18"
